In [1]:
# Import libraries
import pandas as pd
import os
import numpy as np
import math

# Set working directory
os.chdir('C:\\Users\\aaron\\Desktop\\GitHub\\Thesis\\Python')

In [2]:
# Import data going through all the relevant sheets
df = {
    t: pd.read_excel('data\FootballLineups\Aux0102-1415.xlsx', sheet_name=f"{t}{t+1}")
    .replace(f'/La-Liga-{t}--{t+1}/', '', regex = True)
    .assign(Season = t)
    for t in range(2001,2022)
}

df.keys()

dict_keys([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [3]:
# Concatenate all the keys in one dataframe and keep relevant obs
AUXLINKS = pd.concat(df.values(), ignore_index=True)

AUXLINKS = AUXLINKS[ (AUXLINKS['/'].str.contains('/match/')) | 
                    (AUXLINKS['/'].str.contains('/team/'))]

In [4]:
# Clean observations
AUXLINKS['/'] = AUXLINKS['/'].replace('/team/', '', regex = True)
AUXLINKS['/'] = AUXLINKS['/'].replace('-', ' ', regex = True)

In [5]:
# Define home and away teams variables
AUXLINKS['index'] = np.where( (AUXLINKS['/'].str.contains('match') ), 1, float('nan') )
AUXLINKS['index'] = np.where( (AUXLINKS['index'].shift(1) == 1 ), 2, AUXLINKS['index'])

AUXLINKS = AUXLINKS.rename(columns = {'/' : 'hometeam'})

AUXLINKS['awayteam'] = np.where(
    (AUXLINKS['index'].isna()) & (~AUXLINKS['hometeam'].str.contains('match')),
    AUXLINKS['hometeam'].shift(-2), 
    float('nan'))

AUXLINKS['url'] = np.where(
    AUXLINKS['index'].isna(),
    'https://m.football-lineups.com' + AUXLINKS['hometeam'].shift(-1),
    float('nan'))

AUXLINKS.head()

,hometeam,Season,index,awayteam,url
19,Valencia,2001,NaN,/match/169492/,https://m.football-lineups.comReal Zaragoza
21,Real Zaragoza,2001,NaN,Barcelona,https://m.football-lineups.com/match/169492/
22,/match/169492/,2001,1.0,NaN,NaN
23,Barcelona,2001,2.0,NaN,NaN
25,Rayo Vallecano,2001,NaN,Celta Vigo,https://m.football-lineups.com/match/169493/

In [6]:
# Keep relevant obs
AUXLINKS = AUXLINKS[AUXLINKS['index'].isna()]
AUXLINKS = AUXLINKS[~AUXLINKS['awayteam'].str.contains('match')]
AUXLINKS.head()

,hometeam,Season,index,awayteam,url
21,Real Zaragoza,2001,NaN,Barcelona,https://m.football-lineups.com/match/169492/
25,Rayo Vallecano,2001,NaN,Celta Vigo,https://m.football-lineups.com/match/169493/
29,Osasuna,2001,NaN,Alaves,https://m.football-lineups.com/match/169494/
33,Tenerife,2001,NaN,Athletic Bilbao,https://m.football-lineups.com/match/169495/
37,Real Sociedad,2001,NaN,UD Las Palmas,https://m.football-lineups.com/match/169496/

In [7]:
# Define, drop and order variables
AUXLINKS['match'] = AUXLINKS['hometeam'] + ' vs ' + AUXLINKS['awayteam']

AUXLINKS = AUXLINKS.drop(['index'], axis = 1)

AUXLINKS = AUXLINKS[['url', 'match', 'hometeam', 'awayteam', 'Season']]

In [8]:
# Save as a excel file
AUXLINKS.to_excel('Datasets/FootballLineups/AUXLINKS.xlsx', index = False)
AUXLINKS.head

<bound method NDFrame.head of                                                 url  \
21     https://m.football-lineups.com/match/169492/
25     https://m.football-lineups.com/match/169493/
29     https://m.football-lineups.com/match/169494/
33     https://m.football-lineups.com/match/169495/
37     https://m.football-lineups.com/match/169496/
...                                             ...
33242  https://m.football-lineups.com/match/388687/
33246  https://m.football-lineups.com/match/388690/
33250  https://m.football-lineups.com/match/388688/
33254  https://m.football-lineups.com/match/388689/
33258  https://m.football-lineups.com/match/388686/

                                  match        hometeam  \
21           Real Zaragoza vs Barcelona   Real Zaragoza
25         Rayo Vallecano vs Celta Vigo  Rayo Vallecano
29                    Osasuna vs Alaves         Osasuna
33          Tenerife vs Athletic Bilbao        Tenerife
37       Real Sociedad vs UD Las Palmas   Real Sociedad
...                                 ...             ...
33242  Osasuna vs Espanyol de Barcelona         Osasuna
33246             Alaves vs Real Madrid          Alaves
33250            Mallorca vs Real Betis        Mallorca
33254                  Cadiz vs Levante           Cadiz
33258                Valencia vs Getafe        Valencia

                    awayteam  Season
21                 Barcelona    2001
25                Celta Vigo    2001
29                    Alaves    2001
33           Athletic Bilbao    2001
37             UD Las Palmas    2001
...                      ...     ...
33242  Espanyol de Barcelona    2021
33246            Real Madrid    2021
33250             Real Betis    2021
33254                Levante    2021
33258                 Getafe    2021

[7980 rows x 5 columns]>

# Football Lineup Data

In [9]:
# Import data going through all the relevant sheets
df = {
    t: pd.read_excel(os.path.join(r'data\FootballLineups\HACKIN', f'HACKIN{t}.xlsx'), sheet_name=0)
    .rename(columns={'x1': 'X1', 'x2': 'X2', 'x3': 'X3'})
    for t in range(1,102)
}

df.keys()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101])

In [10]:
# Concatenate all the keys in one dataframe and keep relevant obs
StatsFL = pd.concat(df.values(), ignore_index=True)

# Keep relevant columns and obs
StatsFL = StatsFL[StatsFL['Var.4'].isna()]
StatsFL = StatsFL.drop(['Rate', 'Var.4'], axis = 1)

# Rename variables
StatsFL = StatsFL.rename(columns = {'X1' : 'Home_Team', 'X2' : 'Stats', 'X3' : 'Away_Team'})

StatsFL.head()

,Home_Team,Stats,Away_Team,url
0,18,Shots,14,https://m.football-lineups.com/match/212868/
1,11,Shots on goal,6,https://m.football-lineups.com/match/212868/
2,12,Fouls,13,https://m.football-lineups.com/match/212868/
3,8,Corner Kicks,7,https://m.football-lineups.com/match/212868/
4,3,Offsides,1,https://m.football-lineups.com/match/212868/

In [11]:
# Merge with AUXLINKS data
MergeFootballLineups = pd.merge(StatsFL, AUXLINKS, on = 'url', validate= 'm:1')
MergeFootballLineups.head()

,Home_Team,Stats,Away_Team,url,match,hometeam,awayteam,Season
0,18,Shots,14,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
1,11,Shots on goal,6,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
2,12,Fouls,13,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
3,8,Corner Kicks,7,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
4,3,Offsides,1,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014

In [12]:
# Keep relevant obs and clean data
MergeFootballLineups = MergeFootballLineups[
    (MergeFootballLineups['Stats'] == 'Offsides') |
    (MergeFootballLineups['Stats'] == '% possession') |
    (MergeFootballLineups['Stats'] == 'Fouls')
]

MergeFootballLineups['Stats'] = MergeFootballLineups['Stats'].str.replace(' ', '', regex = True)
MergeFootballLineups['Stats'] = MergeFootballLineups['Stats'].str.replace('%', '', regex = True)

In [13]:
MergeFootballLineups

,Home_Team,Stats,Away_Team,url,match,hometeam,awayteam,Season
2,12,Fouls,13,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
4,3,Offsides,1,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
5,54%,possession,46%,https://m.football-lineups.com/match/212868/,Real Madrid vs Getafe,Real Madrid,Getafe,2014
8,19,Fouls,18,https://m.football-lineups.com/match/212860/,Almeria vs Valencia,Almeria,Valencia,2014
10,3,Offsides,3,https://m.football-lineups.com/match/212860/,Almeria vs Valencia,Almeria,Valencia,2014
...,...,...,...,...,...,...,...,...
39548,5,Offsides,0,https://m.football-lineups.com/match/390428/,Rayo Vallecano vs Levante,Rayo Vallecano,Levante,2021
39549,56%,possession,44%,https://m.football-lineups.com/match/390428/,Rayo Vallecano vs Levante,Rayo Vallecano,Levante,2021
39552,11,Fouls,9,https://m.football-lineups.com/match/390429/,Elche CF vs Getafe,Elche CF,Getafe,2021
39554,2,Offsides,1,https://m.football-lineups.com/match/390429/,Elche CF vs Getafe,Elche CF,Getafe,2021
39555,59%,possession,41%,https://m.football-lineups.com/match/390429/,Elche CF vs Getafe,Elche CF,Getafe,2021

In [14]:
MergeFootballLineups = MergeFootballLineups.reset_index(drop = False)

MergeFootballLineups = MergeFootballLineups.pivot(
    index=['url', 'match', 'hometeam', 'awayteam', 'Season', 'index'],
    columns='Stats',
    values=['Home_Team', 'Away_Team']
)

In [15]:
# Save as a excel file
MergeFootballLineups.to_excel('Datasets/FootballLineups/MergeFootballLineups.xlsx', index = True)

In [16]:
# Import data
MergeFootballLineups = pd.read_excel('Datasets/FootballLineups/MergeFootballLineups.xlsx')

In [17]:
# Adjust data
MergeFootballLineups = MergeFootballLineups.rename(columns = {'Unnamed: 0' : 'url', 'Unnamed: 1' : 'match',
                                                    'Unnamed: 2' : 'hometeam', 'Unnamed: 3' : 'awayteam',
                                                    'Unnamed: 4' : 'Season', 'Unnamed: 5' : 'index',
                                                    'Home_Team' : 'Home_Fouls', 'Unnamed: 7' : 'Home_Offsides',
                                                    'Unnamed: 8' : 'Home_Possession', 'Away_Team' : 'Away_Fouls',
                                                    'Unnamed: 10' : 'Away_Offsides', 'Unnamed: 11' : 'Away_Possession'})
# Drop first two rows
MergeFootballLineups = MergeFootballLineups.iloc[2:]

In [18]:
n = 1
while n > 0:
    vars = ['url', 'match', 'hometeam', 'awayteam', 'Season']
    for var in vars:
        MergeFootballLineups[var] = np.where((MergeFootballLineups[var].isna()), 
                                        MergeFootballLineups[var].shift(1),
                                           MergeFootballLineups[var])
        n = MergeFootballLineups['url'].isna().sum()

In [19]:
MergeFootballLineups = pd.DataFrame(MergeFootballLineups)

In [20]:
# Adjust observations
locality = ['Home', 'Away']
vars = ['Fouls', 'Offsides', 'Possession']

for local in locality:
    for var in vars:
        auxvar = local + '_' + var
        print(auxvar)
        
        if var == 'Possession':
            MergeFootballLineups[auxvar] = MergeFootballLineups[auxvar].str.replace('%', '')
        
        MergeFootballLineups[auxvar] = MergeFootballLineups[auxvar].astype(float)

Home_Fouls
Home_Offsides
Home_Possession
Away_Fouls
Away_Offsides
Away_Possession

In [21]:
MergeFootballLineups['Home_Offsides'] = MergeFootballLineups['Home_Offsides'].shift(+1)
MergeFootballLineups['Home_Fouls'] = MergeFootballLineups['Home_Fouls'].shift(+2)

MergeFootballLineups['Away_Offsides'] = MergeFootballLineups['Away_Offsides'].shift(+1)
MergeFootballLineups['Away_Fouls'] = MergeFootballLineups['Away_Fouls'].shift(+2)

In [22]:
# Drop obs
MergeFootballLineups = MergeFootballLineups[(~MergeFootballLineups['Home_Fouls'].isna()) &
                                            (~MergeFootballLineups['Away_Fouls'].isna()) &
                                            (~MergeFootballLineups['Home_Offsides'].isna()) &
                                            (~MergeFootballLineups['Away_Offsides'].isna())]

# Define variables for fouls in favor
MergeFootballLineups['Home_Fld'] = MergeFootballLineups['Away_Fouls']
MergeFootballLineups['Away_Fld'] = MergeFootballLineups['Home_Fouls']

# Drop duplicates
MergeFootballLineups = MergeFootballLineups.drop(columns = ['index'])
MergeFootballLineups.drop_duplicates(ignore_index = True, inplace = True)

In [23]:
# Standarize the name of teams
def standard_teams(df):
    replacements = {
        'Coruna' : 'Coruña', 'Atletico Madrid' : 'Atlético Madrid',
        'Espanyol de Barcelona' : 'Espanyol', 'Elche CF' : 'Elche',
        'Athletic Bilbao' : 'Athletic Club', 'Real Zaragoza' : 'Zaragoza',
        'Real Valladolid' : 'Valladolid', 'Gijon' : 'Gijón'
    }
    
    variables = ['match', 'hometeam', 'awayteam']
    for vars in variables:
        for old_value, new_value in replacements.items():
            df[vars] = df[vars].str.replace(old_value, new_value, regex = True)

# Apply the function
standard_teams(MergeFootballLineups)

In [24]:
# Adjusting for erros in the data

# A list of dictionaries containing all your corrections
match_corrections = [
    {'match': 'Atlético Madrid vs Deportivo La Coruña', 'Season': 2005, 'Home_Possession': 53, 'Away_Possession': 47, 'Home_Fouls': 25, 'Away_Fouls': 26, 'Home_Fld': 26, 'Away_Fld': 25},
    {'match': 'Atlético Madrid vs Sevilla', 'Season': 2005, 'Home_Possession': 68, 'Away_Possession': 32, 'Home_Fouls': 13, 'Away_Fouls': 13, 'Home_Fld': 13, 'Away_Fld': 13, 'Home_Offsides': 1, 'Away_Offsides': 3},
    {'match': 'Zaragoza vs Real Madrid', 'Season': 2006, 'Home_Possession': 45, 'Away_Possession': 55, 'Home_Offsides': 4, 'Away_Offsides': 3},
    {'match': 'Atlético Madrid vs Sevilla', 'Season': 2006, 'Home_Possession': 59, 'Away_Possession': 41, 'Home_Fouls': 23, 'Away_Fouls': 16, 'Home_Fld': 16, 'Away_Fld': 23, 'Home_Offsides': 0, 'Away_Offsides': 4},
    {'match': 'Sevilla vs Levante', 'Season': 2006, 'Home_Possession': 59, 'Away_Possession': 41, 'Home_Fouls': 18, 'Away_Fouls': 25, 'Home_Fld': 25, 'Away_Fld': 18, 'Home_Offsides': 2, 'Away_Offsides': 4},
    {'match': 'Sporting Gijón vs Barcelona', 'Season': 2008, 'Home_Possession': 32, 'Away_Possession': 68, 'Home_Offsides': 0, 'Away_Offsides': 0},
    {'match': 'Tenerife vs Mallorca', 'Season': 2009, 'Home_Possession': 50, 'Away_Possession': 50},
    {'match': 'Barcelona vs Real Sociedad', 'Season': 2010, 'Home_Fld': 9, 'Away_Fld': 9, 'Away_Offsides': 6},
    {'match': 'Rayo Vallecano vs Zaragoza', 'Season': 2011, 'Home_Possession': 61, 'Away_Possession': 39, 'Home_Fouls': 19, 'Away_Fouls': 14, 'Home_Fld': 14, 'Away_Fld': 19, 'Home_Offsides': 0, 'Away_Offsides': 4},
    {'match': 'Valladolid vs Levante', 'Season': 2013, 'Home_Possession': 67, 'Away_Possession': 33, 'Home_Fouls': 13, 'Away_Fouls': 16, 'Home_Fld': 16, 'Away_Fld': 13},
    {'match': 'Levante vs Elche', 'Season': 2013, 'Home_Possession': 46, 'Away_Possession': 54},
    {'match': 'Real Murcia vs Athletic Club', 'Season': 2007, 'Home_Possession': 55, 'Away_Possession': 45, 'Home_Fouls': 20, 'Away_Fouls': 13, 'Home_Fld': 13, 'Away_Fld': 20, 'Home_Offsides': 6, 'Away_Offsides': 3},
    {'match': 'Real Murcia vs Mallorca', 'Season': 2007, 'Home_Possession': 56, 'Away_Possession': 44, 'Home_Fouls': 19, 'Away_Fouls': 18, 'Home_Fld': 18, 'Away_Fld': 19, 'Home_Offsides': 4, 'Away_Offsides': 5},
    {'match': 'Sevilla vs Valladolid', 'Season': 2007, 'Home_Possession': 46, 'Away_Possession': 54, 'Home_Fouls': 16, 'Away_Fouls': 13, 'Home_Fld': 13, 'Away_Fld': 16, 'Home_Offsides': 6, 'Away_Offsides': 2},
    {'match': 'Espanyol vs Real Murcia', 'Season': 2007, 'Home_Possession': 63, 'Away_Possession': 37, 'Home_Fouls': 21, 'Away_Fouls': 20, 'Home_Fld': 20, 'Away_Fld': 21, 'Home_Offsides': 5, 'Away_Offsides': 4},
]

# Create a corrections DataFrame from the list
corrections_df = pd.DataFrame(match_corrections)

corrections_df.head()

,match,Season,Home_Possession,Away_Possession,Home_Fouls,Away_Fouls,Home_Fld,Away_Fld,Home_Offsides,Away_Offsides
0,Atlético Madrid vs Deportivo La Coruña,2005,53.0,47.0,25.0,26.0,26.0,25.0,NaN,NaN
1,Atlético Madrid vs Sevilla,2005,68.0,32.0,13.0,13.0,13.0,13.0,1.0,3.0
2,Zaragoza vs Real Madrid,2006,45.0,55.0,NaN,NaN,NaN,NaN,4.0,3.0
3,Atlético Madrid vs Sevilla,2006,59.0,41.0,23.0,16.0,16.0,23.0,0.0,4.0
4,Sevilla vs Levante,2006,59.0,41.0,18.0,25.0,25.0,18.0,2.0,4.0

In [25]:
corrections_df.columns

Index(['match', 'Season', 'Home_Possession', 'Away_Possession', 'Home_Fouls',
       'Away_Fouls', 'Home_Fld', 'Away_Fld', 'Home_Offsides', 'Away_Offsides'],
      dtype='object')

In [26]:
# Apply corrections
MergeFootballLineups['Home_Possession'] = np.where( (MergeFootballLineups['Home_Possession'] == 0),
                                                  float('nan'), MergeFootballLineups['Home_Possession'])

MergeFootballLineups['Away_Possession'] = np.where( (MergeFootballLineups['Away_Possession'] == 0),
                                                  float('nan'), MergeFootballLineups['Away_Possession'])

MergeFootballLineups = pd.merge(corrections_df, MergeFootballLineups, on = ['match', 'Season'], 
                                how = 'outer', validate = 'one_to_one', indicator = True)

C:\Users\aaron\AppData\Local\Temp\ipykernel_26068\1786316112.py:8: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  MergeFootballLineups = pd.merge(corrections_df, MergeFootballLineups, on = ['match', 'Season'],

In [27]:
locality = ['Home', 'Away']
vars = ['Possession', 'Fouls', 'Fld', 'Offsides']
for local in locality:
    for var in vars:
        auxvar = local + '_' + var
        varx = auxvar + '_x'
        vary = auxvar + '_y'
        
        # Possession
        if var == 'Possession' :
            MergeFootballLineups[vary] = np.where((~MergeFootballLineups[varx].isna()), 
                                                  MergeFootballLineups[varx],
                                                 MergeFootballLineups[vary])
            
        # Fouls
        if (var == 'Fouls') | (var == 'Fld'):
            MergeFootballLineups[vary] = np.where((~MergeFootballLineups[varx].isna()) & 
                                                  (MergeFootballLineups['_merge'] == 'both'),
                                                 MergeFootballLineups[varx],
                                                 MergeFootballLineups[vary])
        # Offsides
        if var == 'Offsides':
            MergeFootballLineups[vary] = np.where(((~MergeFootballLineups[varx].isna()) &
                                                 (MergeFootballLineups['_merge'] == 'both')) |
                                                  (MergeFootballLineups[vary] == 32),
                                                 MergeFootballLineups[varx], MergeFootballLineups[vary])
        
        MergeFootballLineups = MergeFootballLineups.drop(columns = [varx])
        MergeFootballLineups = MergeFootballLineups.rename(columns = {vary : auxvar})

MergeFootballLineups = MergeFootballLineups.drop(columns = ['_merge'])

In [28]:
# Save as a excel file
MergeFootballLineups.to_excel('Datasets/FootballLineups/MergeFootballLineups.xlsx', index = True)

In [29]:
MergeFootballLineups.columns

Index(['match', 'Season', 'url', 'hometeam', 'awayteam', 'Home_Fouls',
       'Home_Offsides', 'Home_Possession', 'Away_Fouls', 'Away_Offsides',
       'Away_Possession', 'Home_Fld', 'Away_Fld'],
      dtype='object')

In [30]:
# Adjusting for Missing Values
manual_insert = {
    'Season': [
        'Temporada 2006/2007', 'Temporada 2006/2007', 'Temporada 2006/2007', 'Temporada 2006/2007',
        'Temporada 2006/2007', 'Temporada 2006/2007', 'Temporada 2006/2007', 'Temporada 2009/2010',
        'Temporada 2009/2010', 'Temporada 2013/2014'
    ],
    'hometeam': [
        'Valencia', 'Gimnàstic', 'Real Sociedad', 'Sevilla',
        'Sevilla', 'Villarreal', 'Atlético Madrid', 'Barcelona',
        'Racing Santander', 'Granada'
    ],
    'awayteam': [
        'Real Sociedad', 'Villarreal', 'Sevilla', 'Betis',
        'Getafe', 'Sevilla', 'Racing Santander', 'Almería',
        'Deportivo La Coruña', 'Celta Vigo'
    ],
    'match': [
        'Valencia vs Real Sociedad', 'Gimnàstic vs Villarreal', 'Real Sociedad vs Sevilla', 'Sevilla vs Betis',
        'Sevilla vs Getafe', 'Villarreal vs Sevilla', 'Atlético Madrid vs Racing Santander', 'Barcelona vs Almería',
        'Racing Santander vs Deportivo La Coruña', 'Granada vs Celta Vigo'
    ],
    
    'homePossession': [53, 61, 47, 51, 50, 52, 66, 73, 51, 49],
    'AwayPossession': [47, 39, 53, 49, 50, 48, 34, 27, 49, 51],
    'HomeFouls': [19, 21, 20, 29, 16, 28, 18, 18, 18, 10],
    'AwayFouls': [19, 14, 16, 24, 19, 18, 24, 14, 12, 14],
    'HomeFld': [19, 14, 16, 24, 19, 18, 24, 14, 12, 14],
    'AwayFld': [19, 21, 20, 29, 16, 28, 18, 18, 18, 10],
    'HomeOffsides': [4, 1, 3, 1, 4, 3, 4, 3, 0, 1],
    'AwayOffsides': [2, 0, 2, 1, 4, 1, 3, 3, 2, 2],
    'url': [''] * 10
}


df = pd.DataFrame(manual_insert)

MergeFootballLineups = pd.concat(MergeFootballLineups, df)


MergeFootballLineups.to_excel('Datasets/FootballLineups/MergeFootballLineups.xlsx', index = True)

#Merge with original data here XXXXX

#MergeFootballLineups['HomeOffsides'] = np.where(MergeFootballLineups['url'] == "https://m.football-lineups.com/match/64162/",
                                              # 0, MergeFootballLineups['HomeOffsides'])
#MergeFootballLineups['AwayOffsides'] = np.where(MergeFootballLineups['url'] == "https://m.football-lineups.com/match/64162/",
                                               #2, MergeFootballLineups['AwayOffsides'])

# Drop duplicates first check if there's any

IndentationError: unexpected indent (2154398234.py, line 46)

In [ ]:
# Adjust Season obs
def standard_teams(df):
    replacements = {
        '20042005' : '0405', '20052006' : '0506',
        '20062007' : '0607', '20072008' : '0708',
        '20082009' : '0809', '20092010' : '0910',
        '20102011' : '1011', '20112012' : '1112',
        '20122013' : '1213', '20132014' : '1314',
        '20142015' : '1415'
    }
    
    for old_value, new_value in replacements.items():
        df['Season'] = df['Season'].str.replace(old_value, new_value, regex = True)

# Apply the function
standard_teams(MergeFootballLineups)

# Adjust the Missing
MergeFootballLineups['HomeFouls'] = np.where((MergeFootballLineups['HomeFld'] == 0) &
                                    (MergeFootballLineups['AwayFld'] == 0), 
                                    float('nan'), MergeFootballLineups['HomeFouls'])

MergeFootballLineups['AwayFouls'] = np.where((MergeFootballLineups['HomeFld'] == 0) &
                                    (MergeFootballLineups['AwayFld'] == 0), 
                                    float('nan'), MergeFootballLineups['AwayFouls'])

MergeFootballLineups['HomeFld'] = np.where((MergeFootballLineups['HomeFouls'].isna()) &
                                    (MergeFootballLineups['AwayFouls'].isna()), 
                                    float('nan'), MergeFootballLineups['HomeFld'])

MergeFootballLineups['AwayFld'] = np.where((MergeFootballLineups['HomeFouls'].isna()) &
                                    (MergeFootballLineups['AwayFouls'].isna()), 
                                    float('nan'), MergeFootballLineups['AwayFld'])

MergeFootballLineups = MergeFootballLineups.rename(columns = {'match' : 'Partido'})

variables = ['hometeam', 'awayteam', 'Partido'] 
for vars in variables:
    MergeFootballLineups[vars] = MergeFootballLineups[vars].str.replace('Betis', 'Real Betis')

In [ ]:
# Save as a excel file
MergeFootballLineups.to_excel('Datasets/FootballLineups/MergeFootballLineups.xlsx', index = False)

# Attendance R Transfermkt

In [ ]:
# Import data going through all the relevant sheets
df = {
    t: pd.read_csv(os.path.join(r'data\FootballLineups\HACKIN\TEAMS - ATTENDANCE', f'Teams{t}.csv'))
    .assign(Year = t)

    for t in range(1998, 2022)
}

print(df.keys())

# Concatenate all the keys in one dataframe and keep relevant obs
AttendanceTeams = pd.concat(df.values(), ignore_index=True)

In [ ]:
# Clean Observations
AttendanceTeams['value'] = AttendanceTeams['value'].str.replace('\t', '')
AttendanceTeams['value'] = AttendanceTeams['value'].str.replace('\n', '')
AttendanceTeams['value'] = AttendanceTeams['value'].str.replace('\r', '')

AttendanceTeams = AttendanceTeams.rename(columns = {'value' : 'hometeam'})

AttendanceTeams['Jornada'] = AttendanceTeams['url'].str[-3:]
AttendanceTeams['Jornada'] = AttendanceTeams['Jornada'].str.replace('g=', '', regex = True)
AttendanceTeams['Jornada'] = AttendanceTeams['Jornada'].str.replace('=', '', regex = True)

parenthesis1 = '('
parenthesis2 = ')'

AttendanceTeams['hometeam'] = AttendanceTeams['hometeam'].str.replace(parenthesis1, '', regex = True)
AttendanceTeams['hometeam'] = AttendanceTeams['hometeam'].str.replace(parenthesis2, '', regex = True)
AttendanceTeams['hometeam'] = AttendanceTeams['hometeam'].str.replace('.', '', regex = True)
AttendanceTeams['hometeam'] = AttendanceTeams['hometeam'].str.replace('\xa0', '', regex = True)

AttendanceTeams['hometeam'] = AttendanceTeams['hometeam'].str.replace(r'\d+', '', regex=True)

AttendanceTeams.head()

In [ ]:
# Standarize the name of the teams
def standard_teams(df):
    replacements = {
        'Almeria' : 'Almería', 'Athletic' : 'Athletic Club', 
        'CA Osasuna' : 'Osasuna', 'Cádiz CF' : 'Cádiz', 
        'Celta de Vigo' : 'Celta Vigo', 'Córdoba CF' : 'Córdoba', 
        'Hércules CF' : 'Hércules', 'Dep La Coruña' : 'Deportivo La Coruña', 
        'Málaga CF' : 'Málaga', 'Racing' : 'Racing Santander', 
        'Sp Gijon' : 'Sporting Gijón', 'Villareal' : 'Villarreal', 
        'CD Leganés' : 'Leganés', 'CD Numancia' : 'Numancia', 
        'CD Tenerife' : 'Tenerife', 'Elche CF' : 'Elche', 
        'RCD Mallorca' : 'Mallorca', 'Real Betis' : 'Betis', 
        'Real Oviedo' : 'Oviedo', 'Real Valladolid' : 'Valladolid', 
        'Real Zaragoza' : 'Zaragoza', 'Recr Huelva' : 'Recreativo', 
        'SD ' : '', 'Sevilla FC' : 'Sevilla', 'UD ' : '', 
        'Xerez CD' : 'Xerez', 'Granada CF' : 'Granada',
        'Santander Santander' : 'Santander'
    }
    
    for old_value, new_value in replacements.items():
        df['hometeam'] = df['hometeam'].str.replace(old_value, new_value, regex = True)

# Apply the function
standard_teams(AttendanceTeams)

In [ ]:
# Sort and save data

In [ ]:
# Save as a excel file
AttendanceTeams.to_excel('Datasets/TRANSFERMKT/AttendanceTeams.xlsx', index = False)

In [ ]:
# Import data going through all the relevant sheets
df = {
    t: pd.read_excel(os.path.join(r'data\FootballLineups\HACKIN\TEAMS - ATTENDANCE', f'Attendance{t}.xlsx'))
    .assign(Year = t)

    for t in range(1998, 2022)
}

print(df.keys())

# Concatenate all the keys in one dataframe and keep relevant obs
AttendanceYears = pd.concat(df.values(), ignore_index=True)

In [ ]:
AttendanceYears.head()

In [ ]:
# Clean obs
AttendanceYears['.'] = AttendanceYears['.'].str.replace('\t', '')
AttendanceYears['.'] = np.where( (AttendanceYears['.'].str.contains('day', na = False)), 
                                "", AttendanceYears['.'] )

letters = ['.', '\s', '·', '[a-zA-Z]', 'á', 'é', 'í', 'ó', 'ú', 'ñ', 'Á', '-']

for l in letters:
    AttendanceYears['.'] = AttendanceYears['.'].str.replace(l, '')

# Rename column
AttendanceYears = AttendanceYears.rename(columns = {'.' : 'Attendance'})

# Define Matchweek variable and clean obs
AttendanceYears['Jornada'] = AttendanceYears['url'].str[-3:]
AttendanceYears['Jornada'] = AttendanceYears['Jornada'].str.replace('g/', '', regex = True)
AttendanceYears['Jornada'] = AttendanceYears['Jornada'].str.replace('g=', '', regex = True)
AttendanceYears['Jornada'] = AttendanceYears['Jornada'].str.replace('=', '', regex = True)

In [ ]:
# Drop even obs

In [ ]:
# Define variables

In [ ]:
# Save as a excel file
AttendanceYears.to_excel('Datasets/TRANSFERMKT/AttendanceYears.xlsx', index = False)

In [ ]:
# Merge with AttendanceTeams

In [ ]:
# Save output